version: "3.8"

services:
  web:
    build: .
    container_name: mhondoro_backend
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mhondoro
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=production
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: mhondoro_db
    restart: always
    environment:
      POSTGRES_DB: mhondoro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: mhondoro_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
